# .github/workflows/deploy.yml
name: Deploy to Server

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: '22'
        script: |
          cd /var/www/dashboard.cabriot.com
          source venv/bin/activate
          git pull